### ISSUE TITLE
AttributeError: module 'prose.codeaccelerator' has no attribute 'ReadCsvBuilder'

### ISSUE THREAD

**Issue by iamniv01** [MicrosoftDocs/prose-py-api-docs#56]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0e95d40-ff71-2eec-3782-46f453e34d83
* Version Independent ID: c580c115-5165-6bfc-df3b-b7e53dff6f0c
* Content: [Read a CSV file with the Microsoft PROSE Code Accelerator SDK - Python](https://docs.microsoft.com/en-us/python/api/overview/azure/prose/readcsv?view=prose-py-latest)
* Content Source: [prosepy/docs-ref-conceptual/readcsv.md](https://github.com/MicrosoftDocs/prose-py-api-docs/blob/live/prosepy/docs-ref-conceptual/readcsv.md)
* Service: **non-product-specific**
* GitHub Login: @simmdan
* Microsoft Alias: **dsimmons**

**Comment by simmdan** [comment]
These docs are for version 1.7.0 of the package, and in that version there definitely is a ReadCsvBuilder.  I do not recommend using later versions of the package.
